import OpenAI from 'openai';
import { readFile, mkdir, appendFile } from 'node:fs/promises';
import path from 'node:path'; import { fileURLToPath } from 'node:url'; import { outputSchema } from './schema.js';
const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..'); const pause = ms => new Promise(r => setTimeout(r, ms));
export function stub(input) { const text = `${input.title} ${input.description}`.toLowerCase(); const category = /node|javascript|code|software/.test(text) ? 'technology' : /business|market|startup/.test(text) ? 'business' : /history|biography|science|nonfiction/.test(text) ? 'nonfiction' : /novel|story|fiction/.test(text) ? 'fiction' : 'other'; const flags = [input.description.length < 20 && 'missing_context', input.price > 500 && 'suspicious_price', input.rating <= 2 && 'low_rating'].filter(Boolean); return { category, summary: `${input.title} is classified from the supplied catalogue information.`.slice(0,160), quality_flags: flags.length ? flags : ['none'], confidence: category === 'other' ? 0.35 : 0.9 }; }
const canRetry = e => e?.status === 429 || e?.status >= 500 || e?.name === 'AbortError' || e?.code === 'ETIMEDOUT';
async function call(client, params) { for (let attempt=0;;attempt+=1) { try { return await client.chat.completions.create(params); } catch(e) { if (attempt === 2 || !canRetry(e)) throw e; await pause(250 * 2 ** attempt + Math.random() * 150); } } }
export async function enrichBook(input, env=process.env) {
  if (env.LLM_ENABLED === 'false') return { data: stub(input), meta: { provider:'fallback', promptVersion:'enrich-book-v1', repairs:0 } };
  if (env.LLM_STUB === '1' || !env.LLM_API_KEY) return { data: stub(input), meta: { provider:'stub', promptVersion:'enrich-book-v1', repairs:0 } };
  const prompt = await readFile(path.join(root,'prompts','enrich-book-v1.md'),'utf8'); const client = new OpenAI({apiKey:env.LLM_API_KEY,baseURL:env.LLM_BASE_URL,timeout:Math.min(+env.LLM_TIMEOUT_MS||30000,60000),maxRetries:0}); const started=performance.now(); const messages=[{role:'system',content:prompt},{role:'user',content:JSON.stringify(input)}]; let response=await call(client,{model:env.LLM_MODEL||'openrouter/free',temperature:0,messages}); let raw=response.choices[0]?.message?.content||'';
  for (let repairs=0;repairs<=1;repairs+=1) { try { const data=outputSchema.parse(JSON.parse(raw)); console.info(JSON.stringify({event:'llm_call',promptVersion:'enrich-book-v1',model:env.LLM_MODEL,tokens:response.usage?.total_tokens??null,durationMs:Math.round(performance.now()-started),repairs})); return {data,meta:{provider:'model',promptVersion:'enrich-book-v1',repairs}}; } catch(e) { if (repairs===1) { const dir=path.join(root,'quarantine'); await mkdir(dir,{recursive:true}); await appendFile(path.join(dir,'invalid-output.jsonl'),JSON.stringify({at:new Date().toISOString(),error:e.message,raw})+'\n'); return null; } response=await call(client,{model:env.LLM_MODEL||'openrouter/free',temperature:0,messages:[...messages,{role:'assistant',content:raw},{role:'user',content:`Repair JSON. Validation error: ${e.message}`}]}); raw=response.choices[0]?.message?.content||''; } }
}
